package Ventanas;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.*;
import javax.swing.JPanel;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Usuario
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    ImagenFondo Lprincipal = new ImagenFondo();

    public Principal() {
        this.setContentPane(Lprincipal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLBienve = new javax.swing.JLabel();
        Bluchar = new javax.swing.JButton();
        BCargarGene = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLBienve.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N
        jLBienve.setText("Bienvenido al mundo en guerra");
        jLBienve.setBackground(new java.awt.Color(204, 153, 0));

        Bluchar.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        Bluchar.setText("Luchar");
        Bluchar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlucharActionPerformed(evt);
            }
        });

        BCargarGene.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        BCargarGene.setText("Cargar General");
        BCargarGene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCargarGeneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLBienve, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(BCargarGene, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Bluchar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(153, 153, 153))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLBienve)
                .addGap(48, 48, 48)
                .addComponent(Bluchar)
                .addGap(44, 44, 44)
                .addComponent(BCargarGene)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BlucharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlucharActionPerformed
        /*JButton bcargarGene = new JButton("Selecciona fichero");
        bcargarGene.addActionListener() {}  */
            JFileChooser fileChooser = new JFileChooser();
            Ejercito ejerc = new Ejercito();
            ejerc.setVisible(true);
            this.setVisible(false);
        
    }//GEN-LAST:event_BlucharActionPerformed

    private void BCargarGeneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCargarGeneActionPerformed

        // Creamos un JFileChooser, es una ventana para seleccionar un fichero
        JFileChooser fileChooser = new JFileChooser();

        fileChooser.setDialogTitle("selecciona el fichero");

        // Abrims la ventana, guardamos la opcion seleccionada
        int resultado = fileChooser.showOpenDialog(null);

        //agregamos 3 filtros al selector de ficheros
        FileFilter filter = new FileNameExtensionFilter("Ficheros de excel", "xlsx");
        fileChooser.addChoosableFileFilter(filter);
        FileFilter filter2 = new FileNameExtensionFilter("Ficheros csv", "csv");
        fileChooser.addChoosableFileFilter(filter2);
        FileFilter filter3 = new FileNameExtensionFilter("Ficheros xml", "xml");
        fileChooser.addChoosableFileFilter(filter3);

        // Si se ha seleccionado un fichero, le da en aceptar
        if (resultado == JFileChooser.APPROVE_OPTION) {

            System.out.println(fileChooser.getSelectedFile());

            Ejercito ejercito = new Ejercito();
            ejercito.setVisible(true);
            this.setVisible(false);

        }
}//GEN-LAST:event_BCargarGeneActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCargarGene;
    private javax.swing.JButton Bluchar;
    private javax.swing.JLabel jLBienve;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    class ImagenFondo extends JPanel {

        //Atributos
        private Image imagen;

        //Metodos
        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("Imagenes/Lejercito.jpeg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);

        }
    }

}
